### ISSUE TITLE
btnx-config won't detect my MX Revolution Mouse

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [cdobrich/btnx-config#1]
Ubuntu 13.10 on an ASUS M70SA.  Ubuntu knows I have a MX Revolution mouse, but btnx-config won't allow me to set the 'Enable revoco' option, saying it isn't detected.

I have set the product field to "Logitech MX Revolution Mouse", but left the Vendor blank.

I have tried setting the Hot-plugging & WAIT_FOR_SYSFS udev options in all possible combinations but btnx-config still doesn't recognise my MX Revolution mouse.

I have, however, been able to add ALL the buttons using the "Detect mouse & buttons" function. (Though btnx-config hung up on me a few times whilst doing it, it eventually worked.)

Cheers,
Nap

This is of my devices:
 egrep "Name|Handlers" /proc/bus/input/devices
N: Name="Sleep Button"
H: Handlers=kbd event0 
N: Name="Lid Switch"
H: Handlers=event1 
N: Name="Power Button"
H: Handlers=kbd event2 
N: Name="AT Translated Set 2 keyboard"
H: Handlers=sysrq kbd event3 
N: Name="Asus Laptop extra buttons"
H: Handlers=rfkill kbd event4 
N: Name="Video Bus"
H: Handlers=kbd event5 
N: Name="HDA Intel Headphone"
H: Handlers=event6 
N: Name="HDA Intel Headphone"
H: Handlers=event7 
N: Name="HDA Intel Mic"
H: Handlers=event8 
N: Name="USB 2.0 Camera"
H: Handlers=kbd event9 
N: Name="IR-receiver inside an USB DVB receiver"
H: Handlers=kbd event10 
N: Name="ITE8708 CIR transceiver"
H: Handlers=kbd event11 
N: Name="MCE IR Keyboard/Mouse (ite-cir)"
H: Handlers=sysrq kbd mouse0 event12 
N: Name="HDA ATI HDMI HDMI/DP,pcm=3"
H: Handlers=event14 
N: Name="Logitech MX Revolution Mouse"
H: Handlers=kbd mouse2 event15 
N: Name="btnx keyboard"
H: Handlers=sysrq rfkill kbd event13 js0 
N: Name="btnx mouse"
H: Handlers=mouse1 event16

**Comment by cdobrich** [comment]
Sorry for the delayed reply. I have not forgotten about you. I cannot see any problems with the compiling process. Next questions:

What are the names of the Configuration Profile(s) you have used? I only recently noticed a bug with whitespace in the Configuration Names. This didn't seem to happen on older versions of Fedora, only the latest one.

Also, open a console and run btnx-config from there, and grab the console output, then share that please.

**Comment by Napoleon-BlownApart** [comment]
I'm going to have to re-assemble my mouse.  I've taken it to pieces to fix something but haven't put it back together again :-|
