### ISSUE TITLE
udev's transition to systemd

### ISSUE THREAD

**Issue by cdobrich** [cdobrich/btnx-config#5]
When trying to compile BTNX-Config under a fresh install of Fedora 21 Linux 3.19.3-200.fc21.x86_64 today, I got this error message:
```
udev.c: In function ‘udev_create’:
udev.c:78:4: warning: too many arguments for format [-Wformat-extra-args]
    mouse_get_vendor_id(), mouse_get_product_id());
    ^
udev.c:84:4: warning: too many arguments for format [-Wformat-extra-args]
    mouse_get_vendor_id(), mouse_get_product_id());
    ^
```

I am fairly certain this has to do with some changes in the underlying system involving udev's transition to systemd. Ugh. I hope this is an easier fix than it looks like.

**Comment by cdobrich** [comment]
The latest changes to udev.c I made seem to have fixed this problem.

**Comment by Rdrk-MX** [comment]
On Ubuntu 16.04 the udev rule (located at /etc/udev/rules.d/99-btnx.rules) had these values:

```
BUS=="usb", SYSFS{idVendor}=="1bcf", SYSFS{idProduct}=="0005", ACTION=="add", RUN+="/etc/init.d/btnx start"

BUS=="usb", SYSFS{idVendor}=="1bcf", SYSFS{idProduct}=="0005", ACTION=="remove", RUN+="/etc/init.d/btnx stop"
```
It seems that BUS ans SYSFS are now deprecated so systemd btnx.service was entering in a failure state code=151.

So I changed it to this in order to work properly:
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1bcf", ATTRS{idProduct}=="0005", ACTION=="add", RUN+="/etc/init.d/btnx start"

SUBSYSTEMS=="usb", ATTRS{idVendor}=="1bcf", ATTRS{idProduct}=="0005", ACTION=="remove", RUN+="/etc/init.d/btnx stop"
```
Hope it helps Ubuntu (and Debian derivated) users. 

Cheers!
